#!/bin/bash

#------------------------------------------------------------------------------
# Configuration variables
#------------------------------------------------------------------------------

# Command line flags
INSTALLPKGS=false
INSTALLFLATPAKS=false
INSTALLFONTS=false
EXPORTPACKAGES=false
IMPORTPACKAGES=false
IMPORTFILE=""

# Export file paths
RPMOUTPUTFILE="./fedora-packages-rpm.txt"
CONFOUTPUTFILE="./packages-exported.conf"

# Batch sizes for package installation
BATCH_SIZE=30
SMALL_BATCH_SIZE=20

# List of flatpaks to install
FLATPAKS=(
  "app.zen_browser.zen"
)

# Font URLs
CARTOGRAPH_FONT_URL="https://github.com/g5becks/Cartograph/archive/refs/heads/main.zip"
CARTOGRAPH_FONT_DIR="$HOME/.local/share/fonts/CartographCF/"

#------------------------------------------------------------------------------
# Functions
#------------------------------------------------------------------------------

# Print the logo
printlogo() {
    cat << "EOF"
    ______
   / ____/_  ___________  ____ _________
  / /_  / / / / ___/ __ \/ __ `/ ___/ _ \ fedora system crafting tool
 / __/ / /_/ / /  / / / / /_/ / /__/  __/ original by: typecraft
/_/    \__,_/_/  /_/ /_/\__,_/\___/\___/  fork by: ellipticobj

EOF
}

# Show help message
showhelp() {
  echo "usage: $0 [OPTION]"
  echo "options:"
  echo "  -h, --help                 display this help message"
  echo "  -a, --all                  install everything (default)"
  echo "  -p, --packages             install packages from packages.conf"
  echo "  -f, --flatpaks             install flatpaks"
  echo "  -t, --fonts                install fonts"
  echo "  -d, --download [FILENAME]  install packages from a file"
  echo "  -e, --export               export currently installed packages to files"
  echo "                             creates $RPMOUTPUTFILE and $CONFOUTPUTFILE"
  echo "  -c, --current              export and install currently installed packages"
  echo
}

# install everything if no args
if [ $# -eq 0 ]; then
  INSTALLPKGS=true
  INSTALLFLATPAKS=true
  INSTALLFONTS=true
fi

while [[ $# -gt 0 ]]; do
  case $1 in
    -h|--help)
      showhelp
      exit 0
      ;;
    -a|--all)
      INSTALLPKGS=true
      INSTALLFLATPAKS=true
      INSTALLFONTS=true
      shift
      ;;
    -p|--packages)
      INSTALLPKGS=true
      shift
      ;;
    -f|--flatpaks)
      INSTALLFLATPAKS=true
      shift
      ;;
    -t|--fonts)
      INSTALLFONTS=true
      shift
      ;;
    -e|--export)
      EXPORTPACKAGES=true
      shift
      ;;
    -d|--download)
      IMPORTPACKAGES=true
      if [[ -n "$2" && ! "$2" =~ ^- ]]; then
        IMPORTFILE="$2"
        shift
      else
        IMPORTFILE="fedora-packages-rpm.txt"
      fi
      shift
      ;;
    -c|--current)
      EXPORTPACKAGES=true
      IMPORTPACKAGES=true
      shift
      ;;
    *)
      echo "unknown option: $1"
      showhelp
      exit 1
      ;;
  esac
done

# clear screen and show logo
printlogo

# exit on any error
set -e

# export packages if requested
if [[ "$EXPORTPACKAGES" == true ]]; then
  echo "exporting currently installed packages..."
  echo "exporting installed packages to $RPMOUTPUTFILE and $CONFOUTPUTFILE..."

  # export to rpm text format
  echo "# fedora packages installed on $(date)" > "$RPMOUTPUTFILE"
  echo "# generated by furnace" >> "$RPMOUTPUTFILE"
  echo "# https://github.com/ellipticobj/furnace" >> "$RPMOUTPUTFILE"
  echo "" >> "$RPMOUTPUTFILE"
  echo "# user-installed packages" >> "$RPMOUTPUTFILE"
  rpm -qa --qf "%{NAME}\n" | sort >> "$RPMOUTPUTFILE"

  # export to packages.conf format
  echo "# Fedora packages installed on $(date)" > "$CONFOUTPUTFILE"
  echo "# Generated by Furnace" >> "$CONFOUTPUTFILE"
  echo "" >> "$CONFOUTPUTFILE"
  echo "# All packages to install" >> "$CONFOUTPUTFILE"
  echo "PACKAGES=(" >> "$CONFOUTPUTFILE"

  # get the list of installed packages
  rpm -qa --qf "%{NAME}\n" | sort | while read -r package; do
    echo "  $package" >> "$CONFOUTPUTFILE"
  done

  echo ")" >> "$CONFOUTPUTFILE"
  echo "" >> "$CONFOUTPUTFILE"
  echo "# services" >> "$CONFOUTPUTFILE"
  echo "SERVICES=(" >> "$CONFOUTPUTFILE"
  echo "  NetworkManager.service" >> "$CONFOUTPUTFILE"
  echo "  bluetooth.service" >> "$CONFOUTPUTFILE"
  echo ")" >> "$CONFOUTPUTFILE"

  echo "package list exported successfully to $RPMOUTPUTFILE and $CONFOUTPUTFILE"
fi

# import packages if requested
if [[ "$IMPORTPACKAGES" == true ]]; then
  if [[ -z "$IMPORTFILE" ]]; then
    IMPORTFILE="fedora-packages-rpm.txt"
  fi

  if [ ! -f "$IMPORTFILE" ]; then
    echo "Error: Package list file not found: $IMPORTFILE"
    exit 1
  fi

  echo "installing packages from $IMPORTFILE..."

  # read packages from file, skipping comments and empty lines
  PACKAGES=()
  while IFS= read -r line || [ -n "$line" ]; do
    # skip comments and empty lines
    if [[ ! "$line" =~ ^#.*$ ]] && [[ -n "$line" ]]; then
      # check if the package is already installed
      if ! rpm -q "$line" &> /dev/null; then
        PACKAGES+=("$line")
      fi
    fi
  done < "$IMPORTFILE"

  # install packages in batches to avoid command line length issues
  if [ ${#PACKAGES[@]} -ne 0 ]; then
    echo "found ${#PACKAGES[@]} packages to install"

    # install in batches
    TOTAL_PACKAGES=${#PACKAGES[@]}
    BATCHES=$(( (TOTAL_PACKAGES + BATCH_SIZE - 1) / BATCH_SIZE ))

    for ((i=0; i<BATCHES; i++)); do
      START=$((i * BATCH_SIZE))
      END=$(( (i+1) * BATCH_SIZE > TOTAL_PACKAGES ? TOTAL_PACKAGES : (i+1) * BATCH_SIZE ))
      BATCH=("${PACKAGES[@]:START:END-START}")

      echo "Installing batch $((i+1))/$BATCHES ($(( END - START )) packages)..."
      sudo dnf install -y "${BATCH[@]}"
    done

    echo "all packages have been installed"
  else
    echo "no new packages found to install in $IMPORTFILE"
  fi
fi

# install packages from packages.conf
if [[ "$INSTALLPKGS" == true ]]; then
  # source the package list
  if [ ! -f "packages.conf" ]; then
    echo "error: packages.conf not found"
    exit 1
  fi

  source packages.conf

  echo "starting system setup..."

  # update the system first
  echo "updating system..."
  sudo dnf upgrade -y

  # install packages in batches
  installpkgs() {
    local packages=("$@")

    if [ ${#packages[@]} -eq 0 ]; then
      return
    fi

    echo "installing packages..."

    # install in batches to avoid command line length issues
    local totalpackages=${#packages[@]}
    local batches=$(( (totalpackages + SMALL_BATCH_SIZE - 1) / SMALL_BATCH_SIZE ))

    for ((i=0; i<batches; i++)); do
      local start=$((i * SMALL_BATCH_SIZE))
      local end=$(( (i+1) * SMALL_BATCH_SIZE > totalpackages ? totalpackages : (i+1) * SMALL_BATCH_SIZE ))
      local batch=("${packages[@]:start:end-start}")

      echo "installing batch $((i+1))/$batches ($(( end - start )) packages)..."
      sudo dnf install -y "${batch[@]}"
    done
  }

  # install all packages
  installpkgs "${PACKAGES[@]}"

  # enable services
  echo "configuring services..."
  for service in "${SERVICES[@]}"; do
    if ! systemctl is-enabled "$service" &> /dev/null; then
      echo "enabling $service..."
      sudo systemctl enable "$service"
    else
      echo "$service is already enabled"
    fi
  done
fi

# install flatpaks
if [[ "$INSTALLFLATPAKS" == true ]]; then
  echo "installing flatpaks..."

  for pak in "${FLATPAKS[@]}"; do
    if ! flatpak list | grep -i "$pak" &> /dev/null; then
      echo "installing flatpak: $pak"
      flatpak install --noninteractive "$pak"
    else
      echo "flatpak already installed: $pak"
    fi
  done
fi

# Install fonts
if [[ "$INSTALLFONTS" == true ]]; then
  echo "installing fonts..."

  if wget -q https://github.com/g5becks/Cartograph/archive/refs/heads/main.zip; then
    mkdir -p "$HOME/.local/share/fonts/CartographCF/" && unzip -o -q "main.zip" -d "$HOME/.local/share/fonts/CartographCF/" && echo "cartograph CF installed successfully"
  else
    echo
    echo "failed to download cartograph CF :("
  fi
fi

echo "complete!"
